"""Mako template for migration scripts"""

"""Initial schema

Revision ID: 4dd6632f1782
Revises: 
Create Date: 2025-11-19 22:17:08.153639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd6632f1782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('white_player_id', sa.UUID(), nullable=False),
    sa.Column('black_player_id', sa.UUID(), nullable=False),
    sa.Column('initial_setup_json', sa.JSON(), nullable=False),
    sa.Column('current_state_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('from_square', sa.String(length=2), nullable=False),
    sa.Column('to_square', sa.String(length=2), nullable=False),
    sa.Column('piece_type', sa.String(length=10), nullable=False),
    sa.Column('captured_piece', sa.String(length=10), nullable=True),
    sa.Column('promotion_piece', sa.String(length=10), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=True),
    sa.Column('is_checkmate', sa.Boolean(), nullable=True),
    sa.Column('is_castling', sa.Boolean(), nullable=True),
    sa.Column('is_en_passant', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
